CREATE TABLE profiles(

    id BINARY(16) NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
);

INSERT INTO profiles VALUES (1, "ROLE_ADMIN");
INSERT INTO profiles VALUES (2, "ROLE_CONSUMER")